# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .sass-cache

# Site Settings
locale: "en-CA"
site_theme: "default"
title: "Anson Hammell"
name: "Anson"
dessciption: "Resume for Anson Hammell"
url: https://athammell.github.io
baseurl: ""
repository: "athammell/athammell.github.io"

# Site Author & Persons Information
resume_name: "Anson T. Hammell"
resume_title: "Front End Web Devloper"
resume_contact_email: "anson.hammell@outlook.com"
resume_contact_telephone: ""

# Socials
resume_github: "https://github.com/athammell"

# Site Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
